#!/usr/bin/env bash
# Configures Nginx with a custom X-Served-By response header
# shellcheck disable=SC2154

sudo apt-get update -y
sudo apt-get install -y nginx

sudo cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;
    add_header X-Served-By $hostname;
}
EOF

sudo service nginx restart