#!/usr/bin/env bash
# Configures Nginx with a custom X-Served-By response header
# shellcheck disable=SC2154

apt update -y
apt install nginx -y

new_config=\
"server {
    listen 80 default_server;
    server_name _;

    root /var/www/html;
    index index.html;
    add_header X-Served-By $(hostname);
}"

echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null
service nginx restart