#!/usr/bin/env bash
# Installs and configures HAProxy


sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
# Configure HAProxy frontend and backend
tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend frontend_cluster
    bind *:80
    default_backend backend_cluster

backend backend_cluster
    balance roundrobin
    server 6987-web-01 13.218.71.202:80 check
    server 6987-web-02 3.82.213.44:80 check
EOF

service haproxy restart