#!/usr/bin/env bash
# Installs and configures Nginx to return "Holberton School" at root

sudo apt-get update -y
sudo apt-get install -y nginx

sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html

sudo service nginx restart