#!/usr/bin/env bash
# Configures Nginx with a 301 redirect on /redirect_me

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

# Add redirect rule before the first location / block
sed -i '0,/location \/ {/s//location \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation \/ {/' /etc/nginx/sites-available/default

service nginx restart