#!/usr/bin/env bash
# Configures Nginx with a custom 404 page saying "Ceci n'est pas une page"

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

bash -c "cat > /etc/nginx/sites-available/default << 'EOF'
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        location / {
                try_files \$uri \$uri/ =404;
        }
}
EOF"

nginx -t && service nginx restart

curl localhost/nonexistent