#!/usr/bin/env bash
# Configures Nginx with a custom 404 page saying "Ceci n'est pas une page"

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add custom 404 error page directive
sed -i '/listen \[::\]:80 default_server;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Add redirect
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx restart